blank_issues_enabled: true
contact_links:
  - name: 获取插件用法 (本仓库)
    url: https://github.com/UnrealMultiple/TShockPlugin?tab=readme-ov-file#%E5%B7%B2%E6%94%B6%E9%9B%86%E6%8F%92%E4%BB%B6
    about: 点击链接即可跳转的相关用法
  - name: 获取插件用法 (论坛+文档站)
    url: https://tr.monika.love/resources/104/
    about: 点击链接即可跳转的相关用法
  - name: TShock官方群
    url: https://jq.qq.com/?_wv=1027&k=5GJZCe4
    about: 如果你不会使用Github，可以加入TShock官方QQ群交流
  - name: 不会解压ZIP
    url: https://ys.mihoyo.com/main/
    about: 去米友社提问
