name: 报告BUG | Report a Bug
description: 提交一个本仓库插件BUG | Submit a bug for this repository plugin
title: '[BUG] '
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        很高兴你能提交新的Bug，为了能够更好的解决问题，请你填写下面的表格捏 | We are glad you are submitting a new bug. To better solve the problem, please fill out the form below.
  - type: checkboxes
    id: read3
    attributes:
      label: BUG可复现 | Bug is reproducible
      description: 我已确保我复现BUG的方法可用 | I confirm that the method to reproduce the bug is valid
      options:
        - label: 是 | Yes
          required: true
  - type: checkboxes
    id: read4
    attributes:
      label: 插件最新 | Plugin is up-to-date
      description: 我已确保我的插件是最新版本 | I confirm that my plugin is the latest version
      options:
        - label: 是 | Yes
          required: true

  - type: input
    id: plugin-name
    attributes:
      label: 插件名字 | Plugin Name
      description: 出问题的插件 | Plugin with the issue
      placeholder: CaiBotPlugin
    validations:
      required: true

  - type: input
    id: tshock-version
    attributes:
      label: TShock版本 | TShock Version
      description: TShock版本 | TShock Version
      placeholder: 5.2.3
    validations:
      required: true

  - type: dropdown
    id: system
    attributes:
      label: 系统 | System
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么? | What happened?
      description: 填写对问题的描述 | Describe the issue
      placeholder: |
        输入/slap Cai 结果给Koko打了一巴掌 | Entered /slap Cai and ended up slapping Koko
    validations:
      required: true
  - type: textarea
    id: how-reproduce
    attributes:
      label: 如何复现 | How to reproduce
      description: 填写应当如何操作才会让BUG出现 | Describe the steps to reproduce the bug
      placeholder: |
        1. 输入/slap Cai | 1. Enter /slap Cai
        2. 然后打了Koko | 2. Then slapped Koko
        3. xxx
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: 期望的结果? | Expected result?
      description: 填写如果你觉得插件正常，会出现的结果 | Describe the expected result if the plugin works correctly
      placeholder: |
        输入/slap Cai 会打Cai一巴掌 | Entering /slap Cai will slap Cai
    validations:
      required: true

  - type: textarea
    id: text-log
    attributes:
      label: 文本日志 | Text log
      description: tshock文本日志的不正常、报错部分 | Abnormal or error parts of the tshock text log
      render: shell
      placeholder: |
        2024-07-17 11:34:58 - Utils: INFO: Server执行了/slap Cai。
        2024-07-17 11:34:58 - Slap: ERROR: System.Exception: 数据库初始化错误：连接MySQL失败。查看内部异常以获取详细信息。
        ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: ChestID'.
        at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
        at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
        at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
        at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
        at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
        at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
        at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
        at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args)
        --- End of inner exception stack trace ---
        at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args)
        at CaiRewardChest.Db.GetChestById(Int32 chestId) in C:\Users\13110\source\repos\CaiPlugins\CaiRewardChest\Db.cs:line 35
        at CaiRewardChest.Db.GetChestByPos(Int32 x, Int32 y) in C:\Users\13110\source\repos\CaiPlugins\CaiRewardChest\Db.cs:line 29
        at CaiRewardChest.CaiRewardChest.OnChestOpen(Object sender, ChestOpenEventArgs e) in C:\Users\13110\source\repos\CaiPlugins\CaiRewardChest\Plugin.cs:line 39
        at TShockAPI.HandlerList`1.Invoke(Object sender, T e)
        at TShockAPI.GetDataHandlers.OnChestOpen(MemoryStream data, Int32 x, Int32 y, TSPlayer player)
        at TShockAPI.GetDataHandlers.HandleChestOpen(GetDataHandlerArgs args)
      
  - type: textarea
    id: console-log
    attributes:
      label: 控制台日志 | Console log
      description: 在控制台的报错截图或文本，没有请忽略 | In the console’s error screenshots or text, ignore if none.
      render: shell
      placeholder: |
        Server执行了/slap Cai。
        ERROR: System.Exception: 数据库初始化错误：连接MySQL失败。查看内部异常以获取详细信息。
        ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: ChestID'.
        at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
        at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
        at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
        at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
        at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
        at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
        at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
        at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args)
        --- End of inner exception stack trace ---
        at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args)
        at CaiRewardChest.Db.GetChestById(Int32 chestId) in C:\Users\13110\source\repos\CaiPlugins\CaiRewardChest\Db.cs:line 35
        at CaiRewardChest.Db.GetChestByPos(Int32 x, Int32 y) in C:\Users\13110\source\repos\CaiPlugins\CaiRewardChest\Db.cs:line 29
        at CaiRewardChest.CaiRewardChest.OnChestOpen(Object sender, ChestOpenEventArgs e) in C:\Users\13110\source\repos\CaiPlugins\CaiRewardChest\Plugin.cs:line 39
        at TShockAPI.HandlerList`1.Invoke(Object sender, T e)
        at TShockAPI.GetDataHandlers.OnChestOpen(MemoryStream data, Int32 x, Int32 y, TSPlayer player)
        at TShockAPI.GetDataHandlers.HandleChestOpen(GetDataHandlerArgs args)
      

